name: GitHub Actions Demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_ENV: development
  MY_HOST: '127.0.0.1'
  FULLNAME: 'John Wor'
jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello ${{ github.actor }} $FULLNAME"
        - run: echo "My host is ${{ env.MY_HOST }}"
        - run: echo " ${{ vars.COMPANY_NAME }}"
        - run: echo " ${{ secrets.DB_PASSWORD }}"
    test-job:
      runs-on: ubuntu-latest
      needs: build-job # use "needs" for job dependencies
      steps:
        - run: echo "Repo is ${{ github.repository }}"
    deploy-job:
      needs: test-job
      runs-on: ubuntu-latest
      steps:
        - run: echo "Deploying the application ${{ job.status }}"
