name: GitHub Actions Demo
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Building the application"
    test-job:
      runs-on: ubuntu-latest
      needs: build-job
      steps:
        - run: echo "Testing the application"
    deploy-job:
      needs: test-job
      runs-on: ubuntu-latest
      steps:
        - run: echo "Deploying the application"
